# ===============================
# API GATEWAY
# ===============================
server.port=8080
spring.application.name=api-gateway

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true

# ===============================
# RUTAS
# ===============================

spring.cloud.gateway.routes[0].id=usuario-service
spring.cloud.gateway.routes[0].uri=lb://usuario-service
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/usuarios/**

spring.cloud.gateway.routes[1].id=propiedad-service
spring.cloud.gateway.routes[1].uri=lb://propiedad-service
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/propiedades/**

spring.cloud.gateway.routes[2].id=reservas-service
spring.cloud.gateway.routes[2].uri=lb://reservas-service
spring.cloud.gateway.routes[2].predicates[0]=Path=/api/reservas/**

spring.cloud.gateway.routes[3].id=pagos-service
spring.cloud.gateway.routes[3].uri=lb://pagos-service
spring.cloud.gateway.routes[3].predicates[0]=Path=/api/pagos/**

spring.cloud.gateway.routes[4].id=auth-service
spring.cloud.gateway.routes[4].uri=lb://auth-service
spring.cloud.gateway.routes[4].predicates[0]=Path=/api/auth/**

spring.cloud.gateway.routes[5].id=contrato-service
spring.cloud.gateway.routes[5].uri=lb://contrato-service
spring.cloud.gateway.routes[5].predicates[0]=Path=/api/contratos/**

spring.cloud.gateway.routes[6].id=documento-service
spring.cloud.gateway.routes[6].uri=lb://documento-service
spring.cloud.gateway.routes[6].predicates[0]=Path=/api/documentos/**

spring.cloud.gateway.routes[7].id=mantenimiento-service
spring.cloud.gateway.routes[7].uri=lb://mantenimiento-service
spring.cloud.gateway.routes[7].predicates[0]=Path=/api/mantenimiento/**

spring.cloud.gateway.routes[8].id=notificaciones-service
spring.cloud.gateway.routes[8].uri=lb://notificaciones-service
spring.cloud.gateway.routes[8].predicates[0]=Path=/api/notificaciones/**

spring.cloud.gateway.routes[9].id=opiniones-service
spring.cloud.gateway.routes[9].uri=lb://opiniones-service
spring.cloud.gateway.routes[9].predicates[0]=Path=/api/opiniones/**

spring.cloud.gateway.routes[10].id=promociones-service
spring.cloud.gateway.routes[10].uri=lb://promociones-service
spring.cloud.gateway.routes[10].predicates[0]=Path=/api/promociones/**

spring.cloud.gateway.routes[11].id=visita-service
spring.cloud.gateway.routes[11].uri=lb://visita-service
spring.cloud.gateway.routes[11].predicates[0]=Path=/api/visitas/**

logging.level.root=INFO
logging.level.com.inmobiliaria=DEBUG
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n