# Puerto estandar para el Gateway
server.port=8080

# Nombre identificador en la red de microservicios
spring.application.name=api-gateway

# Configuracion para encontrar servicios automaticamente por su nombre
spring.cloud.gateway.discovery.locator.enabled=true
spring.cloud.gateway.discovery.locator.lower-case-service-id=true

# Ubicacion del servidor de descubrimiento (Eureka)
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

eureka.instance.prefer-ip-address=true

