# Puerto del microservicio
server.port=8083

# Nombre identificador para Eureka y el Gateway
spring.application.name=reservas-service

# Configuración de Base de Datos (MySQL)
# Asegúrate de haber creado la base de datos 'db_reservas' en MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/db_reservas?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=tu_password_aqui
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Registro en el Servidor Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

# Configuración crítica para Mac (M1/M2) y Docker
# Esto asegura que el servicio se registre con su IP real y no con 'localhost'
eureka.instance.prefer-ip-address=true

# Configuración de Feign (Opcional pero recomendada para depurar)
logging.level.com.inmobiliaria.reservasservice.repository.client=DEBUG