server.port=8083
spring.application.name=reservas-service

# Configuración para Base de Datos H2 (En memoria)
spring.datasource.url=jdbc:h2:mem:db_reservas
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

spring.h2.console.enabled=true
spring.jpa.hibernate.ddl-auto=update

# Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/